# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '')|replace('-', '')|default('0.X'), GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH|default('gUNKNOWN')) %}

{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}
{% set lemon_version = '1.3.1' %}
{% set lemon_md5 = 'e89f887559113b68657eca67cf3329b5' %}
package:
  name: openroad
  version: {{ version }}

source:
  - git_url: https://github.com/The-OpenROAD-Project/OpenROAD.git
    git_rev: master
    patches:
      - sta-add-install-options.patch # to enable sta binary distribution
      - disable-mpl2-and-par.patch # until or-tools dep is added
      - disable-cluster-flops-cmd.patch # until or-tools dep is added      
      - remove-boost-span-deps.patch # to allow older boost
      - opendp-numeric.patch # Fixes error with missing include
      - layouttabs-include-qtglobal.patch # Fixes potential missing Qt include
  - url: http://lemon.cs.elte.hu/pub/sources/lemon-{{ lemon_version }}.tar.gz
    md5: {{ lemon_md5 }}
    folder: third_party/lemon
build:
  # number: 202202031935
  number: {{ environ.get('DATE_NUM') }}
  # string: 20220203_1935_py37
  string: {{ environ.get('DATE_STR') }}_{{ py_suffix }}
  script_env:
    - CI
  ignore_run_exports_from:
    # header-only libraries
    - fmt

requirements:
  build:
    - make
    - cmake >=3.19
    - swig 4.0.2
    - bison
    - git >= 2.0          # cmake needs to be able to find git to establish a version string
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}         # [linux]
    - {{ cdt('libxau-devel') }}         # [linux]
    - {{ cdt('libxext-devel') }}        # [linux]
    - {{ cdt('libxdamage-devel') }}     # [linux]
    - {{ cdt('libxfixes-devel') }}      # [linux]    
    - {{ cdt('libxxf86vm-devel') }}     # [linux]
    - {{ cdt('xorg-x11-proto-devel') }} # [linux]
    - {{ cdt('mesa-libgl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}     # [linux]
    - {{ cdt('libselinux-devel') }}     # [linux]
  host:
    - python {{ python_version }}
    - libboost 1.73
    - eigen 3.3
    - spdlog 1.9
    - tk
    - zlib
    - fmt
    - libgomp                 [not osx]
    - llvm-openmp             [osx]
    - qt >=5.7,<6.0
  run:
    # missing run_exports
    - {{ pin_compatible('libboost', min_pin='x.x', max_pin='x.x') }}
    - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
    - spdlog >=1.9,<1.10

test:
  commands:
    - openroad -version
    - sta -version

about:
  home: https://theopenroadproject.org/
  license: BSD-3-Clause
  summary: OpenROAD is an unified application implementing an RTL-to-GDS Flow.

extra:
  recipe-maintainers:
    - proppy
