{% set version = '%s.0_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: verilator
  version: {{ version }}

source:
  git_rev: master
  git_url: http://git.veripool.org/git/verilator

build:
  detect_binary_files_with_prefix: True
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}       [not osx]
    - {{ compiler('cxx') }}     [not osx]
    - {{ compiler('c') }} 4.0   [osx]
    - {{ compiler('cxx') }} 4.0 [osx]
  host:
    - {{ compiler('c') }}       [not osx]
    - {{ compiler('cxx') }}     [not osx]
    - {{ compiler('c') }} 4.0   [osx]
    - {{ compiler('cxx') }} 4.0 [osx]
    - bison
    - flex
    - zlib
  run:
    - {{ compiler('cxx') }}     [not osx]
    - {{ compiler('cxx') }} 4.0 [osx]
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

test:
  files:
    - test/counter.v
    - test/counter_tb.v
    - test/hello_world.v

about:
  home: http://www.veripool.org/projects/verilator/wiki/Intro
  license: LGPL v3
  summary: 'Verilator is the fastest free Verilog HDL simulator, and beats most commercial simulators.'
