{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: openocd
  version: {{ version }}

source:
  git_rev: master
  git_url: git://repo.or.cz/openocd.git
  patches:
    - digilent-arty.patch
    - digilent-cmod-a7.patch
    - digilent-nexys_video.patch
    - gadgetfactory-papilio_duo.patch
    - numato-neso.patch
    - numato-saturn.patch
    - numato-waxwing.patch
    - fpga-program.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - libftdi
    - libusb
  run:
    - libftdi
    - libusb

test:
  commands:
    - openocd -v

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
