{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('yosys-', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: yosys
  version: {{ version }}

source:
  git_url: https://github.com/timvideos/yosys.git
  git_rev: master
  patches:
    - makefile-conda-config.patch
    - disable-failing-ecp5-mux.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - python 3.7
    - tk
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bison
    - flex
    - iverilog
    - libffi
    - pkg-config
    - python 3.7
    - tk
  run:
    - flex
    - libffi
    - python {{ python }}
    - tk

about:
  home: http://www.clifford.at/yosys/
  license: ISC
  license_file: COPYING
  summary: 'Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.'
