{% set version = "0.20" %}

package:
  name: isl
  version: {{ version }}

source:
  fn: isl-{{ version }}.tar.bz2
  url: http://isl.gforge.inria.fr/isl-{{ version }}.tar.bz2
  md5: cb396f31b24aeeac49840b519741b0e1

build:
  number: 1002
  skip: True   # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("isl", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev        # [win]
    - lld             # [win]
    - posix           # [win]
  host:
    - gmp             # [unix]
  run:
    - gmp             # [unix]

test:
  commands:
    - if not exist %LIBRARY_LIB%\\isl.lib exit 1            # [win]
    - if not exist %LIBRARY_INC%\\isl\\options.h exit 1     # [win]
    - test -f "$PREFIX/lib/libisl.a"            # [unix]
    - test -f "$PREFIX/lib/libisl${SHLIB_EXT}"  # [unix]
    - test -d "$PREFIX/include/isl"             # [unix]

about:
  home: http://isl.gforge.inria.fr/
  license: MIT
  license_family: MIT
  summary: a thread-safe C library for manipulating sets and relations of integer points bounded by affine constraints.

extra:
  recipe-maintainers:
    - frol
    - isuruf
