appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 6dbU6z5+/1u/35OTFYQ3SUmxWl6UAAuzk8xn0fK334u0dr0Pw9fEb2fU5Uh4em1hKotdGhYBSfFdaWVTn9WW+pTOUYrd84Ne7SNShC5RVIu2W5qNqgLrwEeOxeQOvYr9PqL7LqAYFN1BgWJbUvlWRaqEL7d2Atm2eBmLAH3N+z6XpAsS2e5s3fZEZKsLk/16Gag/Ayb6sPe4zbOS7kGL2rJH/U57dAT49F3osjCCbEX7ZpV/uYjqwsxNXX/zI4DFxDuffmNxOs0DsVnV3IS6vG8D3ZCQi3JoLud51EUeJZowk1z7YwMvVGN7862skrr+UJuVg4ukxExkDtbAYRuW65ycR5koDc4WI3IjnbJ7+ryf+MDNT/WpHkb4LdZXMnrTzI00yfB7hbTqTAcey6PUJnusCKMv6uhfVMKv45IypNi6WqGTU8iUpFOljHg4U8Qdt6Gvcj0p9f7//7Wz42kFS0tTPTmiVZudVFZ9QLe9vOn5SkVZ5xmXeEONuEccVLHptCt455/IWucEEfO9tkCaZNJ3KA67JF5BrTIzAhXk0PFXJeCwbI7VLD/UjbELiij9mjYmrDluKfK0XhvPm2sdIsO4AaGXzc1b35KtyOIX0qXvHKAup0Nq/QvS+JYz1AMDOfrVpAa4LxUO/urHbBqknbuH3svLVLJXjD/Dg1gPzPc=}
