# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('yosys-', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
{% set build_string = '%s_libffi%s'|format(DATE_STR, LIBFFI_VERSION|replace('.', '')) %}

package:
  name: symbiflow-yosys
  version: {{ version }}

source:
  git_url: https://github.com/SymbiFlow/yosys.git
  git_rev: master+wip
  patches:
    - makefile-conda-config.patch
    - tests-use-vvp.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325_libffi321
  string: {{ build_string }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}         # [not osx]
    - {{ compiler('cxx') }}       # [not osx]
    - {{ compiler('c') }} 4.*     # [osx]
    - {{ compiler('cxx') }} 4.*   # [osx]
    - make
    - gawk
  host:
    - pkg-config
    - readline
    - bison
    - tk
    - libffi={{ environ.get('LIBFFI_VERSION') }}
    - flex
    - iverilog
  run:
    - readline
    - tk
    - libffi={{ environ.get('LIBFFI_VERSION') }}

test:
  source_files:
    - tests/simple/always01.v
  commands:
    - yosys -V
    - yosys-abc -v 2>&1 | grep compiled
    - yosys -Q -S tests/simple/always01.v

about:
  home: http://www.clifford.at/yosys/
  license: ISC
  license_file: COPYING
  summary: 'Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.'
