{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: yosys-plugins
  version: {{ version }}

source:
  git_url: https://github.com/SymbiFlow/yosys-symbiflow-plugins.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pkg-config
    - readline
    - bison
    - tk
    - libffi
    - flex
    - iverilog
    - yosys
  run:
    - yosys

