# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: tree-sitter-verilog
  version: {{ version }}

source:
  - git_url: https://github.com/tree-sitter/tree-sitter-verilog.git
  - git_url: https://github.com/tree-sitter/py-tree-sitter
    folder: py-tree-sitter

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - nodejs
    - python
    - make

about:
  home: https://github.com/tree-sitter/tree-sitter-verilog
  license: MIT
  license_file: LICENSE
  summary: 'Verilog grammar for tree-sitter'
