# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'| format(GIT_DESCRIBE_TAG | default('0.X'), GIT_DESCRIBE_NUMBER | default(0) | int, GIT_DESCRIBE_HASH | default('gUNKNOWN')) %}

package:
  name: open_pdks.sky130a
  version: {{ version }}

source:
  - git_url: https://github.com/RTimothyEdwards/open_pdks.git
    git_rev: master
  # use url below to prevent submodules
  - url: https://github.com/google/skywater-pdk/archive/49d3c73c2cd8ea42cdae5056440baef0f72e7e42.zip
    folder: skywater-pdk
  - url: https://github.com/google/skywater-pdk-libs-sky130_fd_sc_hd/archive/ac7fb61f06e6470b94e8afdf7c25268f62fbd7b1.zip
    folder: skywater-pdk/libraries/sky130_fd_sc_hd/latest
  - url: https://github.com/google/skywater-pdk-libs-sky130_fd_sc_hvl/archive/4fd4f858d16c558a6a488b200649e909bb4dd800.zip
    folder: skywater-pdk/libraries/sky130_fd_sc_hvl/latest
  - url: https://github.com/google/skywater-pdk-libs-sky130_fd_io/archive/63752cd96d0798468758e929922a8dd3ff103381.zip
    folder: skywater-pdk/libraries/sky130_fd_io/latest
  - url: https://github.com/google/skywater-pdk-libs-sky130_fd_pr/archive/f62031a1be9aefe902d6d54cddd6f59b57627436.zip
    folder: skywater-pdk/libraries/sky130_fd_pr/latest
  - url: https://github.com/StefanSchippers/xschem_sky130/archive/efa7a6c74fa0f978d5ccaa73bf14d35a9fad618d.zip
    folder: xschem_sky130
  - url: https://files.pythonhosted.org/packages/07/1f/3d9ae865addc9ef6cb7b102d7d93e227c46b6e5e94db345cae2a30944efa/dataclasses_json-0.5.6-py3-none-any.whl
    sha256: 1d7f3a284a49d350ddbabde0e7d0c5ffa34a144aaf1bcb5b9f2c87673ff0c76e

build:
  noarch: generic
  # number: 202202031935
  number: {{ environ.get('DATE_NUM') }}
  # string: 20220203_1935
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - autoconf
    - automake
    - make
    - python
    - pip
  host:
    - typing_inspect
    - marshmallow
    - marshmallow-enum
    - magic
  run_constrained:
    - {{ pin_compatible('magic', min_pin='x.x.x', max_pin='x.x.x') }}

test:
  commands:
    - test -d $PREFIX/share/pdk/sky130A/libs.ref/sky130_fd_sc_hd
    - test -d $PREFIX/share/pdk/sky130A/libs.ref/sky130_fd_sc_hvl
    - test -d $PREFIX/share/pdk/sky130A/libs.ref/sky130_fd_io
    - test -d $PREFIX/share/pdk/sky130A/libs.ref/sky130_fd_pr

about:
  home: http://opencircuitdesign.com/open_pdks/
  license: Apache-2.0
  summary: 'PDK installer for open-source EDA tools and toolchains. Distributed with a setup for the Google/SkyWater 130nm process.'

extra:
  recipe-maintainers:
    - proppy
