{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG, GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: magic
  version: {{ version }}

source:
   git_url: https://github.com/RTimothyEdwards/magic
   git_rev: master
   patches:
     - csh.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - CONDA_OUT
    - TEST_PACKAGE

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - tcsh
  host:
    - tcsh
    - cairo
    - m4
    - tk
    - ncurses
    - python>=3.7
    - readline
    - fontconfig
    - xorg-libx11
  run:
    - python>=3.7
    - cairo
    - ncurses
    - readline
    - tk
    - xorg-libx11

about:
  home: http://opencircuitdesign.com/magic/
  license_file: LICENSE
  summary: "Magic is a venerable VLSI layout tool, written in the 1980's at Berkeley by John Ousterhout, now famous primarily for writing the scripting interpreter language Tcl. Due largely in part to its liberal Berkeley open-source license, magic has remained popular with universities and small companies. The open-source license has allowed VLSI engineers with a bent toward programming to implement clever ideas and help magic stay abreast of fabrication technology. However, it is the well thought-out core algorithms which lend to magic the greatest part of its popularity. Magic is widely cited as being the easiest tool to use for circuit layout, even for people who ultimately rely on commercial tools for their product design flow."

