# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG, GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}

package:
  name: klayout
  version: {{ version }}

source:
  git_url: https://github.com/KLayout/klayout.git
  git_rev: master
  patches:
    - force-python-dynamic-link.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325_py37
  string: {{ environ.get('DATE_STR') }}_{{ py_suffix }}
  script_env:
    - CI
    - CONDA_OUT
    - TEST_PACKAGE

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   [linux]
    - {{ cdt('mesa-dri-drivers') }}   [linux]
    - {{ cdt('libselinux') }}         [linux]
    - {{ cdt('libxdamage') }}         [linux]
    - {{ cdt('libxxf86vm') }}         [linux]
    - {{ cdt('libxext') }}            [linux]
    - {{ cdt('libxfixes') }}          [linux]
    - {{ cdt('libxau') }}             [linux]
    - {{ cdt('libxcb') }}             [linux]
    - {{ cdt('expat') }}              [linux]
    - {{ cdt('libpng') }}             [linux]
  host:
    - python {{ python_version }}
    - ruby
    - qt >=5.0,<6.0
    - zlib
  run:
    - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
    - ruby
    - qt >=5.0,<6.0
    - zlib

test:
  commands:
    - klayout -v
  requires:
    - ruby
    - python {{ python_version }}
  downstreams:
    - openlane

about:
  home: https://www.klayout.de/
  summary: 'Your Mask Layout Friend'
  description: |
    - View: Fast and accurate viewing of huge layout files
    - Edit: Draw, modify and transform hierarchical layout
    - Generate: Script layout generators, PCells and layout transformation tools
    - Analyze: Search, verify, and measure layout and code analysis scripts
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://www.klayout.de/doc.html
  dev_url: https://github.com/KLayout/klayout

extra:
  recipe-maintainers:
    - curtisma
    - klayoutmatthias
    - proppy
    - flaport
    - joamatab
