package:
  name: gcc-lm32-elf-nostdc
  version: 5.4.0

source:
  fn: gcc-5.4.0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
  sha256: 608df76dec2d34de6558249d8af4cbee21eceddbcb580d666f7a5a583ca3303a
  patches:
   - stdint.patch

build:
  detect_binary_files_with_prefix: False
  number: 1
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - gcc_linux-64
    - libgcc-ng
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog
    # Arch specific
    - binutils-lm32-elf
  run:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog
    # Arch specific
    - binutils-lm32-elf

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
