{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: icestorm
  version: {{ version }}

source:
  git_url: https://github.com/mithro/icestorm.git
  git_rev: master
  patches:
   - noiceprog.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - msys2:m2w64-toolchain     [win]
    - msys2:m2-base             [win]
    - msys2:m2-make             [win]
    - vs2017_win-64             [win]
    - {{ compiler('c') }}       [not osx]
    - {{ compiler('cxx') }}     [not osx]
    - {{ compiler('c') }} 4.0   [osx]
    - {{ compiler('cxx') }} 4.0 [osx]
  host:
    - pkg-config [not win]
  run:
    - readline  [not win]
    - bison     [not win]
    - tk        [not win]
    - libffi    [not win]
    - flex      [not win]
    - msys2:m2-bison    [win]
    - msys2:m2-flex     [win]
    - msys2:m2-libffi   [win]

about:
  home: http://www.clifford.at/icestorm/
  license_file: COPYING
  summary: 'Project IceStorm aims at documenting the bitstream format of Lattice iCE40 FPGAs and providing simple tools for analyzing and creating bitstream files.'

extra:
  maintainers:
    - Tim 'mithro' Ansell <mithro@mithis.com>
    - HDMI2USB Project - https://hdmi2usb.tv <hdmi2usb@googlegroups.com>
