{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('yosys-', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: yosys
  version: {{ version }}

source:
   git_url: https://github.com/timvideos/yosys.git
   git_rev: master
   patches:
     - makefile-conda-config.patch
     - disable-failing-ecp5-mux.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS
    - CONDA_OUT
    - TEST_PACKAGE

test:                                                      # [osx]
  files:                                                   # [osx]
    - test.sh                                              # [osx]
    - only-test.patch                                      # [osx]
  commands:                                                # [osx]
    - git clone https://github.com/timvideos/yosys.git     # [osx]
    - cd yosys                                             # [osx]
    - git apply ../only-test.patch                         # [osx]
    - cd ..                                                # [osx]
    - bash test.sh                                         # [osx]

requirements:
  build:
    - m2w64-toolchain 5.3.0 [win]
    - m2-make               [win]
    - m2-base 1.0.0         [win]
    - m2-bash 4.3           [win]
    - m2-bison 3.0.4        [win]
    - m2-flex  2.6.0        [win]
    - python 3.7
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - m2-base 1.0.0        [win]
    - m2-bison 3.0.4       [win]
    - m2-flex 2.6.0        [win]
    - m2-libreadline 6.3   [win]
    - bison                [not win]
    - flex                 [not win]
    - libffi               [not win]
    - pkg-config           [not win]
    - python 3.7
    - tk   [osx]
    - gawk [osx]
  run:
    - python {{ python }}
    - tk       [osx]
    - gawk     [osx]
    - iverilog [osx]

about:
  home: http://www.clifford.at/yosys/
  license: ISC
  license_file: COPYING
  summary: 'Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.'
