{% set version = '%s.0_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: verilator
  version: {{ version }}

source:
  git_rev: master
  git_url: http://git.veripool.org/git/verilator

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bison
    - flex
  run:
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

test:
  commands:

about:
  home: http://www.veripool.org/projects/verilator/wiki/Intro
  license: LGPL v3
  summary: 'Verilator is the fastest free Verilog HDL simulator, and beats most commercial simulators.'
