{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
# cmake 1.15 required for boost 1.71
{% set boost_version = ">=1.67,<1.68.0a0" %}

package:
  name: nextpnr-ice40
  version: {{ version }}

source:
  git_url: https://github.com/timvideos/nextpnr.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}       [not osx]
    - {{ compiler('cxx') }}     [not osx]
    - {{ compiler('c') }} 4.0   [osx]
    - {{ compiler('cxx') }} 4.0 [osx]
    - m2-base    [win]
    - fontconfig [not win]
    - cmake
    - python 3.7
    - boost     {{ boost_version }}
    - boost-cpp {{ boost_version }}
    - libboost  {{ boost_version }}
    - py-boost  {{ boost_version }}
  host:
    - m2-bison   [win]
    - m2-flex    [win]
    - bison      [not win]
    - eigen      [not win]
    - flex       [not win]
    - pkg-config [not win]
    - patchelf   [linux]
    - icestorm
    - python 3.7
    - boost     {{ boost_version }} [not win]
    - boost-cpp {{ boost_version }} [not win]
    - libboost  {{ boost_version }} [not win]
    - py-boost  {{ boost_version }} [not win]
  run:
    - libgcc-ng    [linux]
    - libstdcxx-ng [linux]
    - icestorm
    - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
    - libboost {{ boost_version }} [not win]
    - py-boost {{ boost_version }} [not win]
    - yosys
    - python
    

test:
  commands:
    - nextpnr-ice40 -V

about:
  home: https://github.com/YosysHQ/nextpnr
  license: ISC
  license_file: COPYING
  summary: 'nextpnr aims to be a vendor neutral, timing driven, FOSS FPGA place and route tool.'
