# Use `conda-build-prepare` before building for a better version string.
{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
{% set boost_version = "1.73.0" %}
{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}

package:
  name: nextpnr-ice40
  version: {{ version }}

source:
  git_url: https://github.com/YosysHQ/nextpnr.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}_{{ py_suffix }}
  script_env:
    - CI

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-base    [win]
    - fontconfig [not win]
    - make       [not win]
    - cmake
    - python {{ python_version }}
  host:
    - m2-bison   [win]
    - m2-flex    [win]
    - bison      [not win]
    - eigen      [not win]
    - flex       [not win]
    - pkg-config [not win]
    - patchelf   [linux]
    - icestorm
    - boost     {{ boost_version }} [not win]
    - boost-cpp {{ boost_version }} [not win]
    - libboost  {{ boost_version }} [not win]
    - py-boost  {{ boost_version }} [not win]
    - python {{ python_version }}
  run:
    - libgcc-ng    [linux]
    - libstdcxx-ng [linux]
    - icestorm
    - libboost {{ boost_version }} [not win]
    - py-boost {{ boost_version }} [not win]
    - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}


test:
  commands:
    - nextpnr-ice40 -V

about:
  home: https://github.com/YosysHQ/nextpnr
  license: ISC
  license_file: COPYING
  summary: 'nextpnr aims to be a vendor neutral, timing driven, FOSS FPGA place and route tool.'
