package:
  name: gcc-or1k-elf-newlib
  version: git

source:
  git_url: https://github.com/openrisc/or1k-gcc.git
  git_rev: or1k-5.4.0-20170218

extra:
  sources:
    newlib:
      git_url: https://github.com/openrisc/newlib.git
      git_rev: v2.4.0

build:
  detect_binary_files_with_prefix: False
  number: 1

requirements:
  build:
    # These are taken from the output of the configure scripts
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog
    # Arch specific
    - binutils-or1k-elf
    - gcc-or1k-elf-nostdc
  run:
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl
    - cloog
    # Arch specific
    - binutils-or1k-elf
    - gcc-or1k-elf-nostdc

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
