{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: arachne-pnr
  version: {{ version }}

source:
  git_url: https://github.com/mithro/arachne-pnr.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ os.environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ os.environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bison
    - flex
    - icestorm
    - iverilog
    - libffi
    - libgcc-ng
    - pkg-config
    - readline
    - tk
    - yosys
  run:
    - icestorm
  {% for package in resolved_packages('host') %}
    - {{ package }}
  {% endfor %}
  {% for package in resolved_packages('build') %}
    - {{ package }}
  {% endfor %}

about:
  home: http://www.clifford.at/arachne-pnr/
  license_file: COPYING
  summary: 'Arachne-pnr implements the place and route step of the hardware compilation process for FPGAs. It accepts as input a technology-mapped netlist in BLIF format, as output by the Yosys [0] synthesis suite for example. It currently targets the Lattice Semiconductor iCE40 family of FPGAs. Its output is a textual bitstream representation for assembly by the IceStorm icepack command. The output of icepack is a binary bitstream which can be uploaded to a hardware device. Together, Yosys, arachne-pnr and IceStorm provide an fully open-source Verilog-to-bistream tool chain for iCE40 1K and 8K FPGA development. Yosys is a framework for Verilog RTL synthesis. It currently has extensive Verilog-2005 support and provides a basic set of synthesis algorithms for various application domains.'

extra:
  maintainers:
    - Tim 'mithro' Ansell <mithro@mithis.com>
    - HDMI2USB Project - https://hdmi2usb.tv <hdmi2usb@googlegroups.com>
