{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: moore
  version: {{ version }}

source:
  git_url: https://github.com/fabianschuiki/moore
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

test:
  commands:
    - moore --version

about:
  home: https://github.com/fabianschuiki/moore
  license: MIT
  license_file: LICENSE-MIT
  summary: HDL compiler based on LLHD
