.. |SHIELD:svg:CI:eda:Upload| image:: https://img.shields.io/github/workflow/status/hdl/conda-eda/Upload/master?longCache=true&style=flat-square&label=Upload%20packages&logo=Github%20Actions&logoColor=fff
   :alt: GitHub Actions workflow 'Upload'
   :height: 22
   :target: https://github.com/hdl/conda-eda/actions/workflows/Upload.yml
.. |SHIELD:png:CI:eda:Upload| image:: https://raster.shields.io/github/workflow/status/hdl/conda-eda/Upload/master?longCache=true&style=flat-square&label=Upload%20packages&logo=Github%20Actions&logoColor=fff
   :alt: GitHub Actions workflow 'Upload'
   :height: 22
   :target: https://github.com/hdl/conda-eda/actions/workflows/Upload.yml
