{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('-','_') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}
package:
  name: vtr
  version: {{ version }}

source:
  git_url: https://github.com/SymbiFlow/vtr-verilog-to-routing.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bison
    - cmake
    - flex
    - pkg-config
    - tbb
    - tbb-devel
  run:
    - tbb

#test:
#  commands:
#    - ./run_reg_test.pl vtr_reg_basic
#    - ./run_reg_test.pl vtr_reg_strong -j2

about:
  home: http://verilogtorouting.org/
  license: MIT
  license_file: LICENSE.md
  summary: 'The Verilog-to-Routing (VTR) project is a world-wide collaborative effort to provide a open-source framework for conducting FPGA architecture and CAD research and development. The VTR design flow takes as input a Verilog description of a digital circuit, and a description of the target FPGA architecture.'
