{% set version = environ.get('XILINX_VIVADO_VERSION') %}

package:
  name: xilinx-vivado
  version: {{ version }}

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

about:
  summary: 'Conda metapackage for Xilinx Vivado SDK. Package checks only Vivado version.'
