{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: symbiflow-toolchain
  version: {{ version }}

source:
  git_url: https://github.com/SymbiFlow/symbiflow-arch-defs.git
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI

requirements:
  build:
    - wget
    - curl
  host:
  run:

about:
  home: https://github.com/SymbiFlow/symbiflow-arch-defs
  license: ISC
  license_file: LICENSE
  summary: 'FOSS architecture definitions of FPGA hardware useful for doing PnR device generation.'
