{% set ns = namespace(surelog_version='0.0', verilator_version='0.0') %}
{% for package in resolved_packages('host') %}
  {% if package.startswith( 'surelog-uhdm ' ) %}
    {% set ns.surelog_version = package.split()[1] %}
  {% endif %}
  {% if package.startswith( 'verilator-uhdm ' ) %}
    {% set ns.verilator_version = package.split()[1] %}
  {% endif %}
{% endfor %}

{% set python_version = PYTHON_VERSION | default('3.7') %}
{% set py_suffix = 'py%s'|format(python_version|replace('.', '')) %}

package:
  name: uhdm-integration-verilator
  version: {{ ns.verilator_version }}

build:
  string: {{ DATE_STR }}_{{ py_suffix }}

requirements:
  host:
    - surelog-uhdm=*={{ DATE_STR }}_{{ py_suffix }}
    - verilator-uhdm=*={{ DATE_STR }}
  run:
    - surelog-uhdm={{ ns.surelog_version }}={{ DATE_STR }}_{{ py_suffix }}
    - verilator-uhdm={{ ns.verilator_version }}={{ DATE_STR }}
